site_name: Արեն Պապյան - Fab Academy
site_description: Fab Academy documentation site
site_author: Արեն Պապյան
copyright: Copyright 2026 Արեն Պապյան - Creative Commons Attribution Non Commercial

site_url: http://fibasile.fabcloud.io/fabacademy-student-template/

nav:
  - Տուն: index.md
  - Իմ մասին: about\index.md
  - Առաջադրանքներ:
      - Շաբաթ 01: assignments/week01.md
      - Շաբաթ 02: assignments/week02.md
      - Շաբաթ 03: assignments/week03.md
      - Շաբաթ 04: assignments/week04.md
      - Շաբաթ 05: assignments/week05.md
      - Շաբաթ 06: assignments/week06.md
      - Շաբաթ 07: assignments/week07.md
      - Շաբաթ 08: assignments/week08.md
      - Շաբաթ 09: assignments/week09.md
      - Շաբաթ 10: assignments/week10.md
      - Շաբաթ 11: assignments/week11.md
      - Շաբաթ 12: assignments/week12.md
      - Շաբաթ 13: assignments/week13.md
      - Շաբաթ 14: assignments/week14.md
      - Շաբաթ 15: assignments/week15.md
      - Շաբաթ 16: assignments/week16.md
      - Շաբաթ 17: assignments/week17.md
      - Շաբաթ 18: assignments/week18.md
      - Շաբաթ 19: assignments/week19.md
      - Շաբաթ 20: assignments/week20.md
  - Նախագծեր:
    - Final Project: projects/final-project.md
    - Sample Project: projects/sample-project.md

extra:

  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fabacademany
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/fabacademany
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabacademany
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/academany"

theme:
  name: material
  language:  en
  palette:
    primary: deep
    accent: indigo
  font:
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/school
  favicon: images/favicon.svg
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
