site_name: Արեն Պապյան - Fab School
site_description: Fab School documentation site
site_author: Արեն Պապյան
copyright: Copyright 2026 Արեն Պապյան - Creative Commons Attribution Non Commercial

site_url: http://fibasile.fabcloud.io/fabacademy-student-template/

nav:
  - 🏠 Տուն: index.md
  - 👤 Իմ մասին: about/index.md
  - 📝 Առաջադրանքներ: assignments/index.md
  - 🚀 Նախագծեր: projects/index.md

theme:
  name: material
  language: en

  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Մուգ ռեժիմ

    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Բաց ռեժիմ

  font:
    text: Noto Sans Armenian
    code: JetBrains Mono

  icon:
    logo: material/school
    favicon: images/favicon.svg

  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - content.code.copy
    - content.action.edit

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fabacademany

    - icon: fontawesome/brands/facebook
      link: https://facebook.com/fabacademany

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabacademany

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/academany

markdown_extensions:
  - attr_list
  - md_in_html
  - extra
  - smarty
  - admonition

  - codehilite:
      guess_lang: false

  - toc:
      permalink: true

plugins:
  - search

  - git-revision-date-localized:
      fallback_to_build_date: true
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]
